FROM node:18-alpine

WORKDIR /app

# Копирование package.json и установка зависимостей
COPY package*.json ./
RUN npm install --silent

# Копирование исходного кода
COPY . .

# Команда запуска
CMD ["npm", "start"]
